import { JourneyCategory, JourneyAd, CategoryId } from './types';

// 6 Ana Kategori - Her biri için farklı kart tasarımı
export const journeyCategories: JourneyCategory[] = [
  {
    id: 'hotel',
    name: 'Hotels & Resorts',
    nameTR: 'Oteller',
    description: 'Lüks konaklama deneyimleri',
    icon: '🏨',
    gradient: 'from-violet-600 via-purple-600 to-indigo-700',
    accentColor: '#8b5cf6',
    cardStyle: 'luxury',
  },
  {
    id: 'beach',
    name: 'Beach & Clubs',
    nameTR: 'Plaj & Kulüpler',
    description: 'Deniz, kum ve eğlence',
    icon: '🏖️',
    gradient: 'from-cyan-500 via-teal-500 to-blue-600',
    accentColor: '#06b6d4',
    cardStyle: 'vibrant',
  },
  {
    id: 'restaurant',
    name: 'Restaurants',
    nameTR: 'Restoranlar',
    description: 'Akdeniz lezzetleri',
    icon: '🍽️',
    gradient: 'from-orange-500 via-red-500 to-rose-600',
    accentColor: '#f97316',
    cardStyle: 'warm',
  },
  {
    id: 'history',
    name: 'Historical Sites',
    nameTR: 'Tarihi Mekanlar',
    description: 'Antik kaleler ve müzeler',
    icon: '🏛️',
    gradient: 'from-amber-600 via-yellow-600 to-orange-700',
    accentColor: '#d97706',
    cardStyle: 'classic',
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    nameTR: 'Eğlence',
    description: 'Gece hayatı ve aktiviteler',
    icon: '🎭',
    gradient: 'from-pink-500 via-fuchsia-500 to-purple-600',
    accentColor: '#ec4899',
    cardStyle: 'dynamic',
  },
  {
    id: 'shopping',
    name: 'Shopping',
    nameTR: 'Alışveriş',
    description: 'Butikler ve AVM\'ler',
    icon: '🛍️',
    gradient: 'from-emerald-500 via-green-500 to-teal-600',
    accentColor: '#10b981',
    cardStyle: 'elegant',
  },
];

// Kategori bazlı reklamlar - Video desteği ile
export const journeyAds: JourneyAd[] = [
  // HOTEL CATEGORY
  {
    id: 'merit-royal',
    categoryId: 'hotel',
    tier: 'platinum',
    name: 'Merit Royal Hotel',
    logo: '👑',
    tagline: 'Akdeniz\'in En Prestijli Adresi',
    description: '5 yıldızlı ultra lüks tatil deneyimi',
    fullDescription: 'Merit Royal Hotel & Spa, dünya standartlarında konaklama, casino, spa ve özel plaj hizmetleri sunar. Michelin yıldızlı şeflerimizle hazırlanan menüler ve VIP hizmetlerle unutulmaz bir tatil.',
    offer: '2 Gece Kal 1 Gece Ücretsiz',
    offerValue: '₺15.000 değerinde',
    couponCode: 'MERITVIP2026',
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200',
    videoUrl: 'https://player.vimeo.com/external/434045526.hd.mp4?s=example',
    location: 'Girne, KKTC',
    distance: '12 dk',
    rating: 4.9,
    reviewCount: 2847,
    priceRange: '₺₺₺₺',
    highlights: ['Özel Plaj', 'Casino', 'Spa & Wellness', '7 Restoran'],
    validUntil: '30 Nisan 2026',
    ctaText: 'Rezervasyon Yap',
    ctaAction: 'reserve',
  },
  {
    id: 'elexus-hotel',
    categoryId: 'hotel',
    tier: 'gold',
    name: 'Elexus Hotel',
    logo: '⭐',
    tagline: 'All-Inclusive Lüks',
    description: 'Aile dostu ultra her şey dahil tatil',
    fullDescription: 'Elexus Hotel, aileniz için mükemmel tatil destinasyonu. Aquapark, çocuk kulübü, gece kulübü ve dünya mutfağından lezzetler.',
    offer: 'Çocuklar Ücretsiz + SPA Hediye',
    offerValue: '₺5.000 değerinde',
    couponCode: 'ELEXUSFAM',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200',
    location: 'Girne, KKTC',
    distance: '15 dk',
    rating: 4.7,
    reviewCount: 1923,
    priceRange: '₺₺₺',
    highlights: ['Aquapark', 'Çocuk Kulübü', 'All-Inclusive', '5 Restoran'],
    validUntil: '31 Mart 2026',
    ctaText: 'Fiyat Al',
    ctaAction: 'reserve',
  },
  {
    id: 'colony-garden',
    categoryId: 'hotel',
    tier: 'bronze',
    name: 'Colony Garden Hotel',
    logo: '🌴',
    tagline: 'Şehrin Kalbinde Huzur',
    description: 'Butik otel deneyimi',
    fullDescription: 'Girne merkezinde, deniz manzaralı butik otel. Açık havuz, spa ve restoran ile rahat konaklama.',
    offer: '%30 İndirim',
    offerValue: '₺2.000 tasarruf',
    couponCode: 'COLONY30',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200',
    location: 'Girne Merkez',
    distance: '5 dk',
    rating: 4.5,
    reviewCount: 856,
    priceRange: '₺₺',
    highlights: ['Deniz Manzarası', 'Açık Havuz', 'Restoran'],
    validUntil: '28 Şubat 2026',
    ctaText: 'Rezervasyon',
    ctaAction: 'reserve',
  },

  // BEACH CATEGORY
  {
    id: 'camelot-beach',
    categoryId: 'beach',
    tier: 'platinum',
    name: 'Camelot Beach Club',
    logo: '🏰',
    tagline: 'Akdeniz\'in En İyi Beach Club\'ı',
    description: 'Premium plaj deneyimi ve eğlence',
    fullDescription: 'Camelot Beach Club, kristal berrak sularda yüzme, VIP kabinler, dünyaca ünlü DJ\'ler ve gurme restoran ile unutulmaz bir gün vaat ediyor.',
    offer: 'VIP Kabin + Şampanya',
    offerValue: '₺3.500 değerinde',
    couponCode: 'CAMELOTVIP',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200',
    videoUrl: 'https://player.vimeo.com/external/beach-party.mp4',
    location: 'Alsancak, Girne',
    distance: '18 dk',
    rating: 4.8,
    reviewCount: 3421,
    priceRange: '₺₺₺',
    highlights: ['VIP Kabinler', 'Su Sporları', 'Canlı DJ', 'Gourmet Restoran'],
    validUntil: '31 Ağustos 2026',
    ctaText: 'Şezlong Ayırt',
    ctaAction: 'book',
  },
  {
    id: 'escape-beach',
    categoryId: 'beach',
    tier: 'gold',
    name: 'Escape Beach',
    logo: '🌊',
    tagline: 'Gün Batımı Partileri',
    description: 'Eğlence dolu plaj deneyimi',
    fullDescription: 'Her gün farklı tematik partiler, su sporları ve lezzetli kokteyller. Gün batımı partileri ile ünlü.',
    offer: 'Şezlong + 2 Kokteyl',
    offerValue: '₺800 değerinde',
    couponCode: 'ESCAPE2026',
    image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200',
    location: 'Alsancak, Girne',
    distance: '20 dk',
    rating: 4.6,
    reviewCount: 2156,
    priceRange: '₺₺',
    highlights: ['Sunset Party', 'Su Sporları', 'Kokteyller'],
    validUntil: '30 Eylül 2026',
    ctaText: 'Rezervasyon',
    ctaAction: 'book',
  },
  {
    id: 'glapsides-beach',
    categoryId: 'beach',
    tier: 'bronze',
    name: 'Glapsides Beach',
    logo: '🐚',
    tagline: 'Doğal Güzellik',
    description: 'Sakin ve huzurlu plaj',
    fullDescription: 'Ailenizle sakin bir gün geçirmek için ideal. Doğal kumsal, temiz deniz ve uygun fiyatlı hizmetler.',
    offer: 'Aile Paketi %25 İndirim',
    offerValue: '₺400 tasarruf',
    couponCode: 'GLAPS25',
    image: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=1200',
    location: 'Gazimağusa',
    distance: '45 dk',
    rating: 4.4,
    reviewCount: 987,
    priceRange: '₺',
    highlights: ['Aile Dostu', 'Temiz Deniz', 'Uygun Fiyat'],
    validUntil: '31 Ekim 2026',
    ctaText: 'Detaylar',
    ctaAction: 'visit',
  },

  // RESTAURANT CATEGORY
  {
    id: 'niazis-restaurant',
    categoryId: 'restaurant',
    tier: 'platinum',
    name: "Niazi's Restaurant",
    logo: '🍖',
    tagline: '1949\'dan Beri Efsane Lezzet',
    description: 'Otantik Kıbrıs mutfağının adresi',
    fullDescription: 'Üç nesil boyunca aynı tariflerle hazırlanan efsanevi şeftali kebabı. Kıbrıs\'ın en ikonik restoranı.',
    offer: 'Meze Tabağı + Tatlı Hediye',
    offerValue: '₺600 değerinde',
    couponCode: 'NIAZI2026',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200',
    videoUrl: 'https://player.vimeo.com/external/kebab-making.mp4',
    location: 'Girne Limanı',
    distance: '8 dk',
    rating: 4.9,
    reviewCount: 4523,
    priceRange: '₺₺',
    highlights: ['Şeftali Kebabı', 'Deniz Manzarası', '75 Yıllık Gelenek'],
    validUntil: '31 Aralık 2026',
    ctaText: 'Menü & Rezervasyon',
    ctaAction: 'menu',
  },
  {
    id: 'bellapais-gardens',
    categoryId: 'restaurant',
    tier: 'gold',
    name: 'Bellapais Gardens',
    logo: '🍷',
    tagline: 'Fine Dining ile Tarihe Yolculuk',
    description: 'Manastır manzaralı romantik akşam yemeği',
    fullDescription: 'Bellapais Manastırı\'nın büyüleyici manzarası eşliğinde dünya mutfağından lezzetler. Romantik akşamlar için mükemmel.',
    offer: 'Şampanya + Özel Menü',
    offerValue: '₺1.200 değerinde',
    couponCode: 'BELLA2026',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200',
    location: 'Bellapais',
    distance: '12 dk',
    rating: 4.8,
    reviewCount: 1876,
    priceRange: '₺₺₺',
    highlights: ['Fine Dining', 'Manastır Manzarası', 'Romantik'],
    validUntil: '31 Mart 2026',
    ctaText: 'Masa Ayırt',
    ctaAction: 'reserve',
  },
  {
    id: 'havana-club',
    categoryId: 'restaurant',
    tier: 'bronze',
    name: 'Havana Club',
    logo: '🍹',
    tagline: 'Latin Lezzetleri',
    description: 'Küba esintili restoran & bar',
    fullDescription: 'Canlı Latin müziği eşliğinde Küba ve Meksika mutfağı. Hafta sonları salsa geceleri.',
    offer: '2. Kokteyl Hediye',
    offerValue: '₺200 değerinde',
    couponCode: 'HAVANA2',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=1200',
    location: 'Girne',
    distance: '10 dk',
    rating: 4.5,
    reviewCount: 1234,
    priceRange: '₺₺',
    highlights: ['Canlı Müzik', 'Kokteyller', 'Dans'],
    validUntil: '28 Şubat 2026',
    ctaText: 'Rezervasyon',
    ctaAction: 'reserve',
  },

  // HISTORY CATEGORY
  {
    id: 'st-hilarion',
    categoryId: 'history',
    tier: 'platinum',
    name: 'St. Hilarion Kalesi',
    logo: '🏰',
    tagline: 'Masallardaki Kale',
    description: 'Disney\'e ilham veren efsanevi kale',
    fullDescription: 'Beşparmak Dağları\'nın zirvesinde, üç katlı masalsı kale. Bizans ve Lusignan dönemlerinden izler taşıyan mimari şaheser.',
    offer: 'Rehberli Tur + Fotoğraf Paketi',
    offerValue: '₺500 değerinde',
    couponCode: 'HILARION2026',
    image: 'https://images.unsplash.com/photo-1599946347371-68eb71b16afc?w=1200',
    videoUrl: 'https://player.vimeo.com/external/castle-tour.mp4',
    location: 'Girne Dağları',
    distance: '25 dk',
    rating: 4.9,
    reviewCount: 3210,
    priceRange: '₺',
    highlights: ['UNESCO Aday', 'Panoramik Manzara', 'Tarih Turu'],
    validUntil: '31 Aralık 2026',
    ctaText: 'Tur Rezervasyonu',
    ctaAction: 'tickets',
  },
  {
    id: 'salamis-ruins',
    categoryId: 'history',
    tier: 'gold',
    name: 'Salamis Harabeleri',
    logo: '🏛️',
    tagline: 'Antik Roma\'nın İzleri',
    description: 'Akdeniz\'in en büyük antik kenti',
    fullDescription: 'M.Ö. 11. yüzyıldan kalma antik kent. Gymnasium, tiyatro ve mozaikler ile Roma döneminin ihtişamı.',
    offer: 'Kombi Bilet %40 İndirim',
    offerValue: '₺300 tasarruf',
    couponCode: 'SALAMIS40',
    image: 'https://images.unsplash.com/photo-1604580864964-0462f5d5b1a8?w=1200',
    location: 'Gazimağusa',
    distance: '50 dk',
    rating: 4.7,
    reviewCount: 2567,
    priceRange: '₺',
    highlights: ['Antik Tiyatro', 'Mozaikler', 'Gymnasium'],
    validUntil: '31 Aralık 2026',
    ctaText: 'Bilet Al',
    ctaAction: 'tickets',
  },
  {
    id: 'bellapais-abbey',
    categoryId: 'history',
    tier: 'bronze',
    name: 'Bellapais Manastırı',
    logo: '⛪',
    tagline: 'Gotik Mimari Şaheseri',
    description: '13. yüzyıldan Gotik manastır',
    fullDescription: 'Kuzey Kıbrıs\'ın en iyi korunmuş Gotik yapısı. Yaz aylarında klasik müzik festivalleri.',
    offer: 'Müzik Festivali Bileti %20',
    offerValue: '₺150 tasarruf',
    couponCode: 'ABBEY20',
    image: 'https://images.unsplash.com/photo-1569251495627-ab946287ff27?w=1200',
    location: 'Bellapais Köyü',
    distance: '12 dk',
    rating: 4.6,
    reviewCount: 1890,
    priceRange: '₺',
    highlights: ['Gotik Mimari', 'Müzik Festivali', 'Manzara'],
    validUntil: '30 Eylül 2026',
    ctaText: 'Detaylar',
    ctaAction: 'visit',
  },

  // ENTERTAINMENT CATEGORY
  {
    id: 'merit-casino',
    categoryId: 'entertainment',
    tier: 'platinum',
    name: 'Merit Casino',
    logo: '🎰',
    tagline: 'KKTC\'nin 1 Numaralı Casino\'su',
    description: 'Las Vegas kalitesinde eğlence',
    fullDescription: 'Canlı oyunlar, slot makineleri, poker turnuvaları ve dünyaca ünlü sanatçı konserleri. VIP salonları ile özel deneyim.',
    offer: '₺1000 Bonus Chip + VIP Giriş',
    offerValue: '₺2.000 değerinde',
    couponCode: 'MERITVIP',
    image: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?w=1200',
    videoUrl: 'https://player.vimeo.com/external/casino-night.mp4',
    location: 'Girne',
    distance: '12 dk',
    rating: 4.8,
    reviewCount: 4567,
    priceRange: '₺₺₺₺',
    highlights: ['Canlı Oyunlar', 'VIP Salon', 'Konserler', '24 Saat'],
    validUntil: '31 Aralık 2026',
    ctaText: 'VIP Rezervasyon',
    ctaAction: 'reserve',
  },
  {
    id: 'club-arma',
    categoryId: 'entertainment',
    tier: 'gold',
    name: 'Club Arma',
    logo: '🎵',
    tagline: 'Gece Hayatının Kalbi',
    description: 'KKTC\'nin en büyük gece kulübü',
    fullDescription: 'Dünyaca ünlü DJ\'ler, 3 farklı dans pisti ve VIP alanlar. Her hafta sonu temalı partiler.',
    offer: 'VIP Masa + Şişe',
    offerValue: '₺1.500 değerinde',
    couponCode: 'ARMANIGHT',
    image: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=1200',
    location: 'Girne',
    distance: '10 dk',
    rating: 4.6,
    reviewCount: 2345,
    priceRange: '₺₺₺',
    highlights: ['DJ Set', 'VIP Masa', '3 Dans Pisti'],
    validUntil: '31 Aralık 2026',
    ctaText: 'Masa Ayırt',
    ctaAction: 'reserve',
  },
  {
    id: 'aqua-park',
    categoryId: 'entertainment',
    tier: 'bronze',
    name: 'Aqua Park Girne',
    logo: '🎢',
    tagline: 'Ailece Eğlence',
    description: 'KKTC\'nin en büyük su parkı',
    fullDescription: '15 farklı kaydırak, dalga havuzu ve çocuk alanları. Tüm aile için eğlence dolu bir gün.',
    offer: 'Aile Bileti %35 İndirim',
    offerValue: '₺400 tasarruf',
    couponCode: 'AQUAFAM35',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200',
    location: 'Alsancak',
    distance: '18 dk',
    rating: 4.4,
    reviewCount: 1567,
    priceRange: '₺₺',
    highlights: ['15 Kaydırak', 'Dalga Havuzu', 'Çocuk Alanı'],
    validUntil: '30 Eylül 2026',
    ctaText: 'Bilet Al',
    ctaAction: 'tickets',
  },

  // SHOPPING CATEGORY
  {
    id: 'city-mall',
    categoryId: 'shopping',
    tier: 'platinum',
    name: 'City Mall Girne',
    logo: '🏬',
    tagline: 'Premium Alışveriş Deneyimi',
    description: '200+ mağaza ile KKTC\'nin en büyük AVM\'si',
    fullDescription: 'Dünya markalarından yerel butiklere, sinema kompleksinden gurme food court\'a kadar her şey bir arada.',
    offer: '₺500 Alışveriş Çeki',
    offerValue: 'Harcama şartsız',
    couponCode: 'CITYMALL500',
    image: 'https://images.unsplash.com/photo-1519567241046-7f570b5e2c0a?w=1200',
    videoUrl: 'https://player.vimeo.com/external/mall-tour.mp4',
    location: 'Girne Merkez',
    distance: '8 dk',
    rating: 4.7,
    reviewCount: 3456,
    priceRange: '₺₺₺',
    highlights: ['200+ Mağaza', 'Sinema', 'Food Court', 'Çocuk Oyun Alanı'],
    validUntil: '28 Şubat 2026',
    ctaText: 'Kampanyaları Gör',
    ctaAction: 'shop',
  },
  {
    id: 'arasta-bazaar',
    categoryId: 'shopping',
    tier: 'gold',
    name: 'Arasta Çarşısı',
    logo: '🧺',
    tagline: 'Otantik Kıbrıs Hediyelikleri',
    description: 'Geleneksel el sanatları ve hediyeler',
    fullDescription: 'Lefke dantelinden, Kıbrıs şaraplarına, el yapımı seramiklerden geleneksel tatlılara kadar otantik hediyeler.',
    offer: '%25 İndirim + Ücretsiz Kargo',
    offerValue: 'Tüm ürünlerde',
    couponCode: 'ARASTA25',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1200',
    location: 'Lefkoşa Surlariçi',
    distance: '35 dk',
    rating: 4.5,
    reviewCount: 1234,
    priceRange: '₺₺',
    highlights: ['El Sanatları', 'Yerel Ürünler', 'Hediyeler'],
    validUntil: '31 Mart 2026',
    ctaText: 'Ürünleri Keşfet',
    ctaAction: 'shop',
  },
  {
    id: 'lemar-hypermarket',
    categoryId: 'shopping',
    tier: 'bronze',
    name: 'Lemar Hypermarket',
    logo: '🛒',
    tagline: 'Her Şey Tek Çatı Altında',
    description: 'Süpermarket ve günlük ihtiyaçlar',
    fullDescription: 'Taze ürünler, ithal gıdalar, elektronik ve ev gereçleri. Online sipariş ve eve teslimat.',
    offer: '%15 İndirim + Anında Teslimat',
    offerValue: '₺100+ alışverişlerde',
    couponCode: 'LEMAR15',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=1200',
    location: 'Tüm KKTC',
    distance: '5 dk',
    rating: 4.3,
    reviewCount: 2890,
    priceRange: '₺',
    highlights: ['Taze Ürünler', 'Eve Teslimat', '24 Saat'],
    validUntil: '31 Ocak 2026',
    ctaText: 'Online Sipariş',
    ctaAction: 'shop',
  },
];

// Kategoriye göre reklamları filtrele
export const getAdsByCategory = (categoryId: CategoryId): JourneyAd[] => {
  return journeyAds.filter(ad => ad.categoryId === categoryId);
};

// Seçilen kategorilere göre kişiselleştirilmiş reklamları getir
export const getPersonalizedAds = (selectedCategories: CategoryId[]): JourneyAd[] => {
  if (selectedCategories.length === 0) return journeyAds;
  
  return journeyAds
    .filter(ad => selectedCategories.includes(ad.categoryId))
    .sort((a, b) => {
      // Tier'a göre sırala
      const tierOrder = { platinum: 0, gold: 1, bronze: 2 };
      return tierOrder[a.tier] - tierOrder[b.tier];
    });
};

// Kategori bilgisini ID'ye göre getir
export const getCategoryById = (id: CategoryId): JourneyCategory | undefined => {
  return journeyCategories.find(cat => cat.id === id);
};
